# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'SHYApproved' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHYApproved

  target 'SHYApprovedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SHYApprovedUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'JSONModel'
pod 'AFNetworking', '~> 3.0'
pod 'IQKeyboardManager', '~> 4.0.9'
pod 'LKDBHelper'
end
